#!/usr/bin/env python3

import math

import rclpy
from rclpy.node import Node

from geometry_msgs.msg import Quaternion

import RPi.GPIO as GPIO
from pan_tilt_cam.PCA9685 import PCA9685

yaw_scale = 180/math.pi
pitch_scale = 180/math.pi

class PanTiltCam(Node):
    '''
    Control node for nodebot1's camera.

    '''
    def __init__(self):
        super().__init__('pan_tilt_cam')
        # subscription for cmd_vel in namespace of nodebot1
        self.subscription = self.create_subscription(
            Quaternion,
            '/local/cmd_cam',
            self.cmd_cam_listener_callback,
            10)

        self.subscription  # prevent unused variable warning
        try:
            self.pwm = PCA9685()
            self.pwm.setPWMFreq(50)
            #self.pwm.setServoPulse(1,500)
            self.center = 87.5
            self.horizontal = 95
            self.pwm.setRotationAngle(0, self.horizontal)
            self.pwm.setRotationAngle(1, self.center)
            self.left_pan = 150
            self.right_pan = 25
            self.down_tilt = 125
            self.up_tilt = 30
        
        except:
            pwm.exit_PCA9685()
            self.get_logger().error('Could not initialize PanTiltHAT')



    def cmd_cam_listener_callback(self, msg):
        self.get_logger().debug('/local/cmd_cam: "%s"' % msg)
        # roll (x-axis rotation)
        sinr_cosp = 2 * (msg.w * msg.x + msg.y * msg.z)
        cosr_cosp = 1 - 2 * (msg.x * msg.x + msg.y * msg.y)
        roll = math.atan2(sinr_cosp, cosr_cosp)
        # pitch (y-axis rotation)
        sinp = 2 * (msg.w * msg.y - msg.z * msg.x)
        if abs(sinp) >= 1:
            # use 90 degrees aka pi/2 if out of range
            if sinp > 0:
                pitch = math.pi/2
            else:
                pitch = -math.pi/2
        else:
            pitch = math.asin(sinp)
        # yaw (z-axis rotation)
        siny_cosp = 2 * (msg.w * msg.z + msg.x * msg.y)
        cosy_cosp = 1 - 2 * (msg.y * msg.y + msg.z * msg.z)
        yaw = math.atan2(siny_cosp, cosy_cosp)
        pan = self.center - yaw_scale * yaw     # servo is upside down
        tilt = self.horizontal + pitch_scale * pitch
        # clamp pan and tilt
        pan = min(pan, self.left_pan)
        pan = max(pan, self.right_pan)
        tilt = min(tilt, self.down_tilt)
        tilt = max(tilt, self.up_tilt)
        self.pwm.setRotationAngle(0, tilt)
        self.pwm.setRotationAngle(1, pan)


def main(args=None):
    rclpy.init(args=args)

    pan_tilt_cam = PanTiltCam()

    rclpy.spin(pan_tilt_cam)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    pan_tilt_cam.destroy_node()
    rclpy.shutdown()



if __name__ == '__main__':
    main()
